name: milpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.7
  - astropy==4.2.1
  - matplotlib==3.4.2
  - numpy==1.21.1
  - pandas==1.3.0
  - spiceypy==4.0.0
  - pyproj==3.1.0
  - Cartopy==0.18.0
  - ephem==4.0.0.2
  - pytz==2021.1
  - scipy==1.7.0
  - Sphinx==4.1.2
  - pydata-sphinx-theme==0.5.2
  - pytest==6.2.4
  - fuzzywuzzy==0.18.0
  - python-Levenshtein==0.12.2
  - openpyxl==3.0.7
  - Jinja2==2.11.3
  - numbers-parser==2.3.13
  - pip==22.1.2
  - pip:
      - subler==0.4.2
      - PyQT5==5.15.4